#!/usr/bin/env bash

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

BACKEND_URL="${BACKEND_URL:-http://localhost:8888}"

cat > static/config.json <<CONFIG
{
  "BACKEND_URL": "${BACKEND_URL}"
}
CONFIG

if [[ -d "public" ]]; then
  cp static/config.json public/config.json
fi
